# Generated by Django 5.2.4 on 2025-07-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
